services:
  price-pusher:
    # Use this to build the price pusher from source. A dependency of the pusher docker
    # image is the pyth-crosschain monorepo lerna docker image. Build lerna image
    # using the following command from the repo root:
    # `docker buildx build -f Dockerfile.lerna -t lerna .`
    #
    # Please note that the docker build from source only works in x86_64 platforms
    # and doesn't work on arm platforms (like Apple M1/M2).
    #
    # build:
    #   context: .

    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v6.6.3
    restart: always
    command:
      - "--"
      - "evm"
      - "--endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://testnet.hashio.io/api"
      - "--private-key-path"
      - "/privatekey"
      # Replace this with the address of the Pyth contract on the EVM network.
      - "--pyth-contract-address"
      - "0xa2aa501b19aff244d90cc15a4cf739d2725b5729"
      - "--price-service-endpoint"
      - "https://hermes.pyth.network" # Replace this with a private Hermes RPC for more reliability
      # - "https://hermes-beta.pyth.network"
      - "--price-config-file"
      - "/price_config"
    configs:
      - privatekey
      - price_config
configs:
  privatekey:
    file: ./mnemonic.txt # Replace this with the path to the mnemonic file
  price_config:
    file: ./price-config.hedera.yaml # Replace this with the path to the price configuration file


# npm run start -- evm --endpoint https://testnet.hashio.io/api \
#     --pyth-contract-address 0xa2aa501b19aff244d90cc15a4cf739d2725b5729 \
#     --price-service-endpoint https://hermes.pyth.network \
#     --price-config-file "./price-config.hedera.yaml" \
#     --mnemonic-file "./mnemonic.txt" 
